In [ ]:
!pip install evaluate Pillow==9.0.0
!pip install pytesseract transformers datasets rouge-score nltk tensorboard py7zr --upgrade

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.4/81.4 KB 3.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 36.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.8/199.8 KB 20.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.2/212.2 KB 25.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.7/468.7 KB 45.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 KB 15.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.9/132.9 KB 17.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 69.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.8/158.8 KB 21.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.6/264.6 KB 30.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 KB 15.8 MB/s eta 0:00:00
  Attempting un

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 31.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 106.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.3/66.3 KB 9.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 113.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 KB 6.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 99.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.7/138.7 KB 18.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 357.2/357.2 KB 33.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.0/93.0 KB 14.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 384.0/384.0 KB 43.5 MB/s eta 0:00:00
  Created wheel for rouge-score: filename=rouge_score-0.1.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!ls

drive  sample_data


In [ ]:
DATAPATH = "drive/MyDrive/CS4248 Team 19/translated_data/final_random_2k_de.csv"
MODELPATH = "drive/MyDrive/CS4248 Team 19/saved_models/flan-t5-small-4lang/"
TOKENIZERPATH = "drive/MyDrive/CS4248 Team 19/saved_models/flan-t5-small-4lang/"

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
tokenizer = AutoTokenizer.from_pretrained(TOKENIZERPATH)

In [ ]:
from transformers import AutoModelForSeq2SeqLM
model = AutoModelForSeq2SeqLM.from_pretrained(MODELPATH).to("cuda:0")

In [ ]:
import pandas as pd

random_de_df = pd.read_csv(DATAPATH).values.tolist()

In [ ]:
print (random_de_df[0][0])
print (random_de_df[0][1])
print (random_de_df[0][2])
print (random_de_df[0][3])
print (random_de_df[0][4])
print (random_de_df[0][5])

0
Eine Person mit braunen Haaren trägt ein blaues Hemd und lila Bandanna um ihren Hals mischt ein Design in eine runde, Ziegelsäule.
Die Person, die ein blaues Hemd trägt, meißelt auf einer Ziegelsäule.
entailment
Eine Person meißelt ein Design aus Ziegelsteinen.
german


In [ ]:
import torch
from sklearn.metrics import classification_report, confusion_matrix

updated_prompts_de = []
for record in random_de_df:
    prem = record[1]
    hypo = record[2]
    text = f"Premise: {prem} Hypothesis: {hypo} Please provide a justification for whether the hypothesis is entailed by the premise, contradicted by the premise, or if it cannot be determined."
    updated_prompts_de.append(text)

In [ ]:
from pprint import pprint

print (updated_prompts_de[0])
print (updated_prompts_de[1])

Premise: Eine Person mit braunen Haaren trägt ein blaues Hemd und lila Bandanna um ihren Hals mischt ein Design in eine runde, Ziegelsäule. Hypothesis: Die Person, die ein blaues Hemd trägt, meißelt auf einer Ziegelsäule. Please provide a justification for whether the hypothesis is entailed by the premise, contradicted by the premise, or if it cannot be determined.
Premise: Zwei Männer sitzen in einem Wohnzimmer, einer trägt kulturelle Kleidung und ein anderer in einem weißen Hemd und Shorts, betrachten auf ihrem Fahrrad und Moped. Hypothesis: Zwei Männer in blauen Anzügen verkaufen Fahrräder und Mopeds. Please provide a justification for whether the hypothesis is entailed by the premise, contradicted by the premise, or if it cannot be determined.


In [ ]:
BS = 50
device = torch.device("cuda:0")

corrupt = []

mapper = {"neutral": 0, "contradiction": 1, "entailment": 2}
y_pred = []
y_test = [mapper[record[3]] for record in random_de_df]

all_pred = []
count = 0

for i in range(0, len(updated_prompts_de), BS):
    batch = updated_prompts_de[i:i+BS]
    inputs = tokenizer(batch, return_tensors="pt", padding=True)

    outputs = model.generate(
                    inputs['input_ids'].to(device),
                    attention_mask=inputs['attention_mask'].to(device),
                    min_length=1,
                    max_new_tokens=40,
                    num_beams=4
                )
    preds = tokenizer.batch_decode(outputs, skip_special_tokens=True)

    for j, pred in enumerate(preds):
        pred_label = pred.split(".")[0].strip().lower()
        pred_expl = pred.split(".")[1].strip().lower()
        if pred_label in ["neutral", "contradiction", "entailment"]:
            y_pred.append(mapper[pred_label])
            if count < 50:
                all_pred.append([
                    pred_label,
                    pred_expl
                ])
                count += 1
        else:
            corrupt.append([pred_label, pred_expl, i, j])

print (len(y_pred))
print (len(y_test))

1999
2000


In [ ]:
pprint (random_de_df[109])

[109,
 'Eine schöne Braut, die mit ihrem neuen Ehemann auf einem Bürgersteig läuft.',
 'Neuvermählte sitzen auf einer Parkbank.',
 'contradiction',
 'Man kann entweder auf einem Bürgersteig gehen oder auf einer Parkbank '
 'sitzen.',
 'german']


In [ ]:
print (corrupt)

[['neuvermählte is neuvermählte', '', 100, 9]]


In [ ]:
del y_test[109]

In [ ]:
cls_data = list(zip(y_test, y_pred))       
cls_data = pd.DataFrame(cls_data, columns=["Actual", "Prediction"])
conf_matrix = confusion_matrix(y_test, y_pred)
cls_report = classification_report(y_test, y_pred)

In [ ]:
print (conf_matrix)

[[276  66 314]
 [267  74 312]
 [189  69 432]]


In [ ]:
print (cls_report)

              precision    recall  f1-score   support

           0       0.38      0.42      0.40       656
           1       0.35      0.11      0.17       653
           2       0.41      0.63      0.49       690

    accuracy                           0.39      1999
   macro avg       0.38      0.39      0.35      1999
weighted avg       0.38      0.39      0.36      1999



In [ ]:
print (len(all_pred))

to_save = []

for item in zip(random_de_df[:50], all_pred):
    idx, prem, hypo, label, expl, _ = item[0] # _ is the language [german]
    pred_label, pred_expl = item[1]

    to_save.append([
        prem,
        hypo,
        label,
        pred_label,
        expl,
        pred_expl
    ])

50


In [ ]:
to_save = pd.DataFrame(to_save, columns=["premise", "hypothesis", "label", "pred_label", "explanation", "pred_explanation"])
to_save.to_csv(f"drive/MyDrive/CS4248 Team 19/Findings/flan-t5-small-4lang-german-eval-first50.csv")